version: "2"
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 443:5000
    volumes:
      - $PWD/data:/var/lib/registry
      - $PWD/certs:/certs:ro
      - $PWD/config/config.yml:/etc/docker/registry/config.yml
  
  auth:
    restart: always
    image: ouwen/docker_auth:latest
    ports: 
      - 5001:5001
    volumes:
      - $PWD/config/auth_config.yml:/config/auth_config.yml:ro
      - $PWD/logs:/logs
      - $PWD/certs:/certs:ro
    environment:
      POSTGRES_CONNECTION: "postgres://postgres:password@postgres:5432/postgres?&sslmode=disable&connect_timeout=10"
    command: ['-log_dir=/logs', '-alsologtostderr=true', '-stderrthreshold=ERROR', '/config/auth_config.yml']
  
  postgres:
    restart: always
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: "password"
    volumes:
      - registry_user_db:/var/lib/postgresql/data

volumes:
  registry_user_db: